services:
  - type: web
    name: tadu-crawler-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "playwright install chromium && python app.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
